title: THORIN
description: THORIN is a tool for mapping Identify-By-Descent (IBD) and inferring the Parent-of-Origin of alleles.
theme: just-the-docs
url: https://rjhfmstr.github.io/thorin


# Aux links for the upper right navigation
aux_links:
  "THORIN on GitHub":
    - "//github.com/RJHFMSTR/THORIN"

